#!/usr/bin/env bash
# bspwmrc

pgrep -x sxhkd > /dev/null || sxhkd &

bspc wm -O %DP-2 HDMI-0
# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 0

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Fix firefox rules. For some reason setting `browser.tabs.inTitlebar`
# to `0` (to remove the border around the window) makes bspwm start
# firefox in `floating` mode.
bspc rule -a firefox state=tiled

# Set background if one is set
if [ -f "$HOME/Pictures/.background" ]; then
    set_bg
fi
# Start polybar service
if ! systemctl --user is-active --quiet polybar; then
    systemctl --user start polybar
fi
# Set default cursor to left pointer
xsetroot -cursor_name left_ptr
# Load pipewire and wireplumber with default.qpwgraph patchbay
qpwgraph -m ~/default.qpwgraph
