#!/usr/bin/env bash
# bspwmrc

pgrep -x sxhkd > /dev/null || sxhkd &

bspc wm -O %DP-2 HDMI-0
# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor DP-2 -d I II III IV V
bspc monitor HDMI-0 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Restore background
BACKGROUND_PATH_FILE="$HOME/.cache/background/path"
if [[ -f $BACKGROUND_PATH_FILE ]]; then
    feh --no-fehbg --bg-fill $(cat $BACKGROUND_PATH_FILE)
fi

# Load default patchbay and noise suppression for microphone
qpwgraph -a -m ~/default.qpwgraph > /dev/null
